# .github/workflows/ci.yml (修正版)

name: CI Checks (Bun)

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "**.png"
      - "**.jpg"
      - "**.jpeg"
      - "**.gif"
      - "**.svg"
      - ".prettierrc"
      - "biome.json"
      - ".husky/**"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-lint:
    name: Build and Lint (Bun)
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run ESLint
        run: bun run lint

      - name: Run Tests
        run: bun run test

      - name: Run Next.js Build
        run: bun run build
