name: Doc Checks

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.md"
      - "docs/**"
  push:
    branches:
      - main
    paths:
      - "**.md"
      - "docs/**"
  workflow_dispatch:

jobs:
  document-only-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Confirm only doc changes
        run: |
          echo "This workflow runs only for documentation or markdown file changes."
          echo "No code checks are performed here."
